version: '3.9'
services:
  app:
    build: .
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/enterprise?schema=public
      - REDIS_URL=redis://redis:6379
      - INTERNAL_ROUTE_HEADER_SECRET=replace-me
      - INTERNAL_ROUTE_PREFIX=internal-secret
      - ADMIN_ROUTE_PREFIX=admin-secret
      - SESSION_SECRET=replace-me
      - EMAIL_TOKEN_SECRET=replace-me
      - NEXT_PUBLIC_INTERNAL_HEADER=replace-me
      - NEXT_PUBLIC_WS_BASE=ws://localhost:3000
    depends_on:
      - postgres
      - redis
      - mailhog
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: enterprise
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '8025:8025'
volumes:
  postgres-data:
